import mongoose from 'mongoose';
import * as dotenv from 'dotenv';
dotenv.config({ path: '.env.local' });

const MONGO_URI = process.env.MONGODB_URI || '';

const SEED_USER = {
  _id: new mongoose.Types.ObjectId(),
  name: 'PromptAll Team',
  username: 'promptall',
  authorName: 'PromptAll Team',
  authorUsername: 'promptall',
};

function slug(title: string) {
  return title.toLowerCase().replace(/[^\w\s-]/g, '').replace(/\s+/g, '-').replace(/-+/g, '-').trim().slice(0, 80) + '-' + Date.now().toString(36) + Math.random().toString(36).slice(2, 5);
}

const PROMPTS = [
  // WRITING (10)
  { title: 'Expert Blog Post Writer', content: `Act as an expert blog writer. Write a comprehensive, SEO-optimized blog post about [TOPIC] that is engaging, well-researched, and actionable. Structure it with:\n- A compelling headline\n- An engaging introduction with a hook\n- 5-7 main sections with subheadings\n- Practical examples and data points\n- A strong conclusion with a call-to-action\n\nTarget audience: [YOUR AUDIENCE]\nTone: [professional/casual/conversational]\nWord count: approximately 1500 words`, category: 'writing', aiTool: 'chatgpt', tags: ['blog', 'seo', 'content', 'writing'], trendingScore: 95, likeCount: 342 },
  { title: 'Viral Short Story Generator', content: `Write a captivating short story (500-800 words) with the following specifications:\n\nGenre: [GENRE - e.g., thriller, romance, sci-fi]\nSetting: [SETTING]\nMain character: [CHARACTER DESCRIPTION]\nConflict: [MAIN CONFLICT]\n\nRequirements:\n- Start with an attention-grabbing first sentence\n- Build tension throughout\n- Include vivid sensory details\n- End with a satisfying or thought-provoking conclusion\n- Use dialogue to reveal character`, category: 'writing', aiTool: 'chatgpt', tags: ['story', 'fiction', 'creative'], trendingScore: 88, likeCount: 287 },
  { title: 'Professional Email Rewriter', content: `Rewrite the following email to be more professional, clear, and persuasive:\n\n[PASTE YOUR EMAIL HERE]\n\nMake it:\n- Concise and scannable\n- Professional but not stiff\n- Clear about the request or information\n- End with a specific call-to-action\n- Appropriate for business communication`, category: 'writing', aiTool: 'chatgpt', tags: ['email', 'business', 'professional'], trendingScore: 92, likeCount: 456 },
  { title: 'Copywriting AIDA Framework', content: `Write compelling sales copy using the AIDA framework for [PRODUCT/SERVICE]:\n\nProduct/Service: [NAME]\nTarget audience: [WHO THEY ARE]\nKey benefit: [MAIN VALUE PROPOSITION]\nPrice point: [PRICE]\n\nATTENTION: Hook that grabs attention immediately\nINTEREST: Build interest with benefits and features\nDESIRE: Create emotional desire through storytelling\nACTION: Clear, urgent call-to-action\n\nKeep total length under 300 words.`, category: 'writing', aiTool: 'claude', tags: ['copywriting', 'marketing', 'sales', 'aida'], trendingScore: 89, likeCount: 312 },
  { title: 'LinkedIn Post That Gets Engagement', content: `Write a LinkedIn post about [TOPIC] that generates high engagement.\n\nContext: I am a [YOUR ROLE] at [COMPANY/INDUSTRY]\nKey insight to share: [YOUR MAIN POINT]\nPersonal experience: [BRIEF STORY OR EXAMPLE]\n\nFormat:\n- Opening hook (1-2 lines, no "I" start)\n- Personal story or data point\n- 3-5 key lessons or takeaways\n- Thought-provoking question at the end\n- Relevant hashtags (3-5)\n\nTone: Authentic, conversational, value-driven\nLength: 150-250 words`, category: 'writing', aiTool: 'chatgpt', tags: ['linkedin', 'social-media', 'personal-brand'], trendingScore: 91, likeCount: 398 },
  { title: 'Academic Essay Structure Builder', content: `Help me write a structured academic essay on: [TOPIC]\n\nRequirements:\n- Thesis statement\n- Introduction with context\n- 3 body paragraphs with topic sentences, evidence, and analysis\n- Counterargument and rebuttal\n- Conclusion that synthesizes main points\n\nAcademic level: [undergraduate/graduate]\nWord count: [TARGET LENGTH]\nCitation style: [APA/MLA/Chicago]\n\nEnsure the essay demonstrates critical thinking, uses formal academic language, and supports claims with evidence.`, category: 'writing', aiTool: 'claude', tags: ['academic', 'essay', 'research'], trendingScore: 85, likeCount: 234 },
  { title: 'YouTube Script Writer', content: `Write a compelling YouTube video script for a [LENGTH]-minute video about [TOPIC].\n\nChannel niche: [YOUR NICHE]\nTarget audience: [AUDIENCE]\nVideo goal: [educate/entertain/sell]\n\nInclude:\n- Hook (first 30 seconds that stops scrolling)\n- B-roll suggestions in [brackets]\n- Natural transitions between sections\n- Engagement prompts (like, subscribe, comment)\n- Strong ending with CTA\n\nTone: [conversational/educational/entertaining]\nMake it sound natural when spoken aloud.`, category: 'writing', aiTool: 'chatgpt', tags: ['youtube', 'script', 'video', 'content'], trendingScore: 87, likeCount: 276 },
  { title: 'Product Description Optimizer', content: `Write an optimized product description for [PRODUCT NAME].\n\nProduct details:\n- Type: [PRODUCT TYPE]\n- Key features: [LIST 3-5 FEATURES]\n- Price: [PRICE]\n- Target customer: [WHO BUYS THIS]\n- Main benefit: [TOP BENEFIT]\n\nWrite in this format:\n1. Headline (benefit-focused, under 10 words)\n2. Opening paragraph (2-3 sentences, lead with benefit)\n3. Features list (5 bullet points, benefit-first format)\n4. Social proof element\n5. Urgency/CTA close\n\nOptimize for both conversions and SEO.`, category: 'writing', aiTool: 'chatgpt', tags: ['ecommerce', 'product', 'seo', 'copywriting'], trendingScore: 90, likeCount: 321 },
  { title: 'Newsletter That People Actually Read', content: `Write a weekly newsletter edition about [TOPIC/NICHE].\n\nNewsletter name: [NAME]\nEdition theme: [THIS WEEK'S THEME]\nMain story: [KEY TOPIC]\n3 secondary topics: [TOPIC 1], [TOPIC 2], [TOPIC 3]\n\nStructure:\n- Subject line (curiosity gap formula)\n- Preview text\n- Personal opener (2-3 sentences)\n- Main story (300-400 words)\n- Quick hits section (3 short items)\n- Recommendation (tool/book/article)\n- Sign-off with personality\n\nTone: Like a smart friend sharing insights.`, category: 'writing', aiTool: 'claude', tags: ['newsletter', 'email', 'content-marketing'], trendingScore: 84, likeCount: 198 },
  { title: 'Book Chapter Outline Creator', content: `Create a detailed chapter outline for a non-fiction book about [TOPIC].\n\nBook details:\n- Genre: Non-fiction / [SUBGENRE]\n- Target reader: [AUDIENCE]\n- Core promise: [WHAT READERS GAIN]\n- Total chapters: [NUMBER]\n\nFor each chapter provide:\n- Chapter title\n- Core concept (1 sentence)\n- 3-5 key points to cover\n- Opening story/example idea\n- Actionable takeaway\n- Transition to next chapter\n\nMake the structure flow logically and build on previous chapters.`, category: 'writing', aiTool: 'claude', tags: ['book', 'outline', 'non-fiction', 'structure'], trendingScore: 82, likeCount: 187 },

  // CODING (10)
  { title: 'Senior Code Reviewer', content: `Act as a senior software engineer conducting a thorough code review. Review the following code:\n\n\`\`\`[LANGUAGE]\n[YOUR CODE HERE]\n\`\`\`\n\nAnalyze for:\n1. **Bugs & Logic Errors**: Any incorrect behavior\n2. **Security Vulnerabilities**: SQL injection, XSS, etc.\n3. **Performance Issues**: Inefficient algorithms, N+1 queries\n4. **Code Quality**: Readability, naming, SOLID principles\n5. **Test Coverage**: What should be tested\n\nProvide specific line-by-line feedback and suggest improved code snippets where relevant.`, category: 'coding', aiTool: 'claude', tags: ['code-review', 'debugging', 'best-practices'], trendingScore: 96, likeCount: 521 },
  { title: 'API Documentation Generator', content: `Generate comprehensive API documentation for the following code:\n\n\`\`\`[LANGUAGE]\n[YOUR API CODE]\n\`\`\`\n\nCreate documentation including:\n- Overview and purpose\n- Authentication requirements\n- Endpoints list with:\n  - HTTP method and path\n  - Description\n  - Request parameters (path, query, body)\n  - Request/Response examples in JSON\n  - Error codes and messages\n- Rate limiting info\n- Code examples in: JavaScript, Python, cURL`, category: 'coding', aiTool: 'chatgpt', tags: ['api', 'documentation', 'rest'], trendingScore: 91, likeCount: 398 },
  { title: 'Debug This Code Expert', content: `I have a bug in my [LANGUAGE] code. Help me debug it.\n\nCode:\n\`\`\`[LANGUAGE]\n[YOUR BUGGY CODE]\n\`\`\`\n\nExpected behavior: [WHAT SHOULD HAPPEN]\nActual behavior: [WHAT IS HAPPENING]\nError message (if any): [ERROR]\n\nPlease:\n1. Identify the root cause\n2. Explain why the bug occurs\n3. Provide the fixed code\n4. Suggest how to prevent similar bugs\n5. Add any relevant tests`, category: 'coding', aiTool: 'claude', tags: ['debug', 'bug-fix', 'troubleshooting'], trendingScore: 94, likeCount: 487 },
  { title: 'SQL Query Optimizer', content: `Optimize the following SQL query for better performance:\n\n\`\`\`sql\n[YOUR SQL QUERY]\n\`\`\`\n\nDatabase: [MySQL/PostgreSQL/SQLite/etc.]\nTable sizes: [approximate row counts]\nCurrent execution time: [if known]\n\nPlease:\n1. Identify performance bottlenecks\n2. Suggest appropriate indexes\n3. Rewrite the optimized query\n4. Explain each optimization\n5. Show EXPLAIN output analysis\n6. Consider edge cases`, category: 'coding', aiTool: 'chatgpt', tags: ['sql', 'database', 'performance', 'optimization'], trendingScore: 88, likeCount: 356 },
  { title: 'React Component Builder', content: `Create a production-ready React component with these specs:\n\nComponent name: [NAME]\nPurpose: [WHAT IT DOES]\nProps needed: [LIST PROPS]\nState management: [local state/context/zustand/redux]\nStyling: [Tailwind CSS/CSS modules/styled-components]\n\nRequirements:\n- TypeScript with proper interfaces\n- Accessibility (ARIA labels, keyboard nav)\n- Error boundary handling\n- Loading states\n- Mobile responsive\n- Unit tests with React Testing Library\n- JSDoc comments\n- Storybook story (optional)`, category: 'coding', aiTool: 'claude', tags: ['react', 'typescript', 'component', 'frontend'], trendingScore: 93, likeCount: 445 },
  { title: 'Python Script Automation Wizard', content: `Write a Python script to automate: [TASK DESCRIPTION]\n\nRequirements:\n- Input: [INPUT DATA/FORMAT]\n- Output: [DESIRED OUTPUT]\n- Handle errors gracefully\n- Add logging\n- Include CLI arguments using argparse\n- Write unit tests\n- Add requirements.txt\n\nConstraints:\n- Python 3.10+\n- Prefer standard library, minimize dependencies\n- Code should be readable and well-commented\n- Include a README with usage examples`, category: 'coding', aiTool: 'chatgpt', tags: ['python', 'automation', 'script'], trendingScore: 90, likeCount: 412 },
  { title: 'System Design Interview Prep', content: `Help me design [SYSTEM NAME] (e.g., URL shortener, Twitter, Netflix).\n\nRequirements:\n- Scale: [expected users/requests per day]\n- Key features: [FEATURE LIST]\n- Constraints: [latency, consistency, availability]\n\nDesign should cover:\n1. Requirements clarification (functional + non-functional)\n2. High-level architecture diagram (text-based)\n3. Database schema design\n4. API design\n5. Scalability considerations\n6. Caching strategy\n7. Load balancing approach\n8. Bottlenecks and solutions`, category: 'coding', aiTool: 'claude', tags: ['system-design', 'architecture', 'interview', 'scalability'], trendingScore: 92, likeCount: 467 },
  { title: 'Unit Test Generator', content: `Generate comprehensive unit tests for the following code:\n\n\`\`\`[LANGUAGE]\n[YOUR CODE]\n\`\`\`\n\nTesting framework: [Jest/Pytest/JUnit/etc.]\n\nCreate tests covering:\n1. Happy path (normal expected behavior)\n2. Edge cases (empty input, max values, etc.)\n3. Error cases (invalid input, exceptions)\n4. Boundary conditions\n5. Mocking external dependencies\n\nFollow AAA pattern (Arrange, Act, Assert) and aim for 90%+ code coverage.`, category: 'coding', aiTool: 'chatgpt', tags: ['testing', 'unit-tests', 'tdd', 'quality'], trendingScore: 87, likeCount: 334 },
  { title: 'Git Commit Message Writer', content: `Write a clear, conventional git commit message for these changes:\n\nFiles changed: [FILE LIST]\nWhat changed: [DESCRIPTION OF CHANGES]\nWhy: [REASON FOR CHANGES]\n\nFollow Conventional Commits format:\n- feat: new feature\n- fix: bug fix\n- docs: documentation\n- refactor: code restructuring\n- test: adding tests\n- chore: maintenance\n\nAlso provide:\n- Short summary (50 chars max)\n- Detailed body explaining the why\n- Breaking change note if applicable\n- Issue reference format`, category: 'coding', aiTool: 'chatgpt', tags: ['git', 'commit', 'version-control'], trendingScore: 83, likeCount: 267 },
  { title: 'Code Refactoring Expert', content: `Refactor the following code to improve quality while maintaining functionality:\n\n\`\`\`[LANGUAGE]\n[YOUR CODE]\n\`\`\`\n\nRefactoring goals:\n1. Apply SOLID principles\n2. Remove code duplication (DRY)\n3. Improve naming conventions\n4. Reduce complexity (aim for <10 cyclomatic complexity)\n5. Extract reusable functions/classes\n6. Add proper error handling\n7. Improve performance where obvious\n\nShow before/after comparison and explain each change.`, category: 'coding', aiTool: 'claude', tags: ['refactoring', 'clean-code', 'solid', 'best-practices'], trendingScore: 89, likeCount: 378 },

  // IMAGE (10)
  { title: 'Cinematic Portrait Photography', content: `[SUBJECT DESCRIPTION], cinematic portrait photography, shot on Hasselblad medium format, 85mm f/1.4 lens, golden hour lighting, bokeh background, shallow depth of field, film grain, Kodak Portra 400, natural skin tones, editorial style, high resolution, award winning photography`, category: 'image', aiTool: 'midjourney', tags: ['portrait', 'photography', 'cinematic', 'realistic'], trendingScore: 94, likeCount: 623 },
  { title: 'Fantasy Character Art', content: `[CHARACTER DESCRIPTION] fantasy character, epic fantasy art style, dramatic lighting, intricate armor/clothing details, magical aura, dynamic pose, ultra-detailed, 8K resolution, by Greg Rutkowski and Artgerm, trending on ArtStation, vibrant colors, cinematic composition, concept art`, category: 'image', aiTool: 'midjourney', tags: ['fantasy', 'character', 'concept-art', 'artstation'], trendingScore: 97, likeCount: 892 },
  { title: 'Architectural Visualization', content: `Modern [BUILDING TYPE] exterior, architectural visualization, photorealistic rendering, golden hour lighting, pristine landscaping, glass and steel facade, minimalist design, ultra high detail, 8K, shot from [LOW/EYE LEVEL/AERIAL] angle, professional architectural photography style, octane render`, category: 'image', aiTool: 'dalle', tags: ['architecture', 'visualization', 'modern', 'realistic'], trendingScore: 88, likeCount: 445 },
  { title: 'Anime Style Character', content: `[CHARACTER DESCRIPTION], anime art style, Studio Ghibli inspired, soft watercolor background, detailed facial features, expressive eyes, beautiful lighting, trending on Pixiv, pastel color palette, clean linework, character illustration, by Makoto Shinkai`, category: 'image', aiTool: 'stable-diffusion', tags: ['anime', 'character', 'ghibli', 'illustration'], trendingScore: 95, likeCount: 756 },
  { title: 'Product Photography on White', content: `[PRODUCT NAME] product photography, pure white background, studio lighting, multiple light sources creating soft shadows, ultra detailed texture, commercial photography quality, 50mm lens equivalent, no distractions, highlight reflections, professional advertising style, high resolution`, category: 'image', aiTool: 'dalle', tags: ['product', 'photography', 'commercial', 'studio'], trendingScore: 86, likeCount: 387 },
  { title: 'Sci-Fi Concept Art Spaceship', content: `[SPACESHIP TYPE] spaceship concept art, hard surface design, detailed mechanical parts, sci-fi aesthetic, deep space background with nebula, dramatic lighting from nearby star, chrome and matte panels, engine glow effects, by John Berkey and Chris Foss, ultra-detailed, 8K`, category: 'image', aiTool: 'midjourney', tags: ['sci-fi', 'spaceship', 'concept-art', 'space'], trendingScore: 91, likeCount: 534 },
  { title: 'Watercolor Landscape Painting', content: `[LANDSCAPE DESCRIPTION] watercolor painting, traditional media look, loose expressive brushstrokes, wet on wet technique, atmospheric perspective, soft colors, white paper texture showing through, professional watercolor illustration, by Joseph Zbukvic, plein air style`, category: 'image', aiTool: 'stable-diffusion', tags: ['watercolor', 'landscape', 'painting', 'traditional'], trendingScore: 84, likeCount: 312 },
  { title: 'Logo Design Minimal', content: `Minimalist logo design for [COMPANY NAME] in the [INDUSTRY] industry, clean vector style, simple geometric shapes, professional and timeless, [PRIMARY COLOR] and [SECONDARY COLOR] color scheme, white background, multiple variations, brand identity design, Adobe Illustrator style`, category: 'image', aiTool: 'dalle', tags: ['logo', 'brand', 'minimal', 'vector', 'design'], trendingScore: 89, likeCount: 478 },
  { title: 'Food Photography Overhead', content: `[DISH NAME] food photography, overhead flat lay composition, rustic wooden table, natural window light, garnished beautifully, professional food styling, props including [RELEVANT PROPS], shallow depth of field on key elements, warm color grading, restaurant quality, commercial photography`, category: 'image', aiTool: 'dalle', tags: ['food', 'photography', 'flat-lay', 'commercial'], trendingScore: 87, likeCount: 423 },
  { title: 'Abstract Digital Art', content: `Abstract [MOOD/EMOTION] digital art, flowing liquid forms, iridescent colors, geometric patterns, light rays, depth and dimension, futuristic aesthetic, dynamic composition, [COLOR PALETTE], ultra high detail, Behance trending, by Beeple and Kintzing, 4K resolution`, category: 'image', aiTool: 'midjourney', tags: ['abstract', 'digital-art', 'nft', 'generative'], trendingScore: 90, likeCount: 567 },

  // BUSINESS (10)
  { title: 'Business Plan Executive Summary', content: `Write a compelling executive summary for a business plan:\n\nBusiness name: [NAME]\nIndustry: [INDUSTRY]\nProduct/Service: [WHAT YOU OFFER]\nTarget market: [WHO YOU SERVE]\nRevenue model: [HOW YOU MAKE MONEY]\nFunding needed: [AMOUNT]\nUse of funds: [HOW YOU'LL USE IT]\n\nCover: problem, solution, market opportunity, business model, competitive advantage, team, financial projections (3 years), funding ask. Keep it under 500 words — make every sentence count.`, category: 'business', aiTool: 'claude', tags: ['business-plan', 'startup', 'executive-summary', 'fundraising'], trendingScore: 93, likeCount: 456 },
  { title: 'SWOT Analysis Generator', content: `Conduct a comprehensive SWOT analysis for [COMPANY/PRODUCT/STRATEGY]:\n\nContext: [BRIEF DESCRIPTION]\nIndustry: [INDUSTRY]\nMain competitors: [COMPETITORS]\nCurrent situation: [CURRENT STATE]\n\nFor each quadrant provide 5-7 specific, actionable points:\n- STRENGTHS: Internal advantages\n- WEAKNESSES: Internal limitations  \n- OPPORTUNITIES: External possibilities\n- THREATS: External risks\n\nAfter the SWOT, provide a strategic summary with 3 recommended actions based on the analysis.`, category: 'business', aiTool: 'chatgpt', tags: ['swot', 'strategy', 'analysis', 'planning'], trendingScore: 90, likeCount: 389 },
  { title: 'Investor Pitch Deck Script', content: `Create a compelling investor pitch for [STARTUP NAME]:\n\nProblem: [THE PROBLEM YOU SOLVE]\nSolution: [YOUR PRODUCT/SERVICE]\nMarket size: [TAM/SAM/SOM]\nBusiness model: [REVENUE STREAMS]\nTraction: [CURRENT METRICS]\nTeam: [KEY MEMBERS]\nAsk: [FUNDING AMOUNT AND TERMS]\n\nWrite slide-by-slide narrative including:\n- Problem slide hook\n- Solution demo talking points\n- Market size with bottom-up analysis\n- Go-to-market strategy\n- Financial highlights\n- The ask with clear value proposition`, category: 'business', aiTool: 'claude', tags: ['pitch', 'investor', 'startup', 'fundraising'], trendingScore: 95, likeCount: 567 },
  { title: 'Customer Persona Creator', content: `Create 3 detailed customer personas for [PRODUCT/SERVICE]:\n\nIndustry: [INDUSTRY]\nProduct: [WHAT YOU SELL]\nPrice point: [PRICE RANGE]\n\nFor each persona provide:\n- Name, age, job title, income\n- Goals and motivations\n- Pain points and frustrations\n- Buying behavior and decision factors\n- Objections to buying your product\n- Preferred communication channels\n- Quote that represents their mindset\n- How your product solves their specific problem\n\nMake personas realistic and distinct from each other.`, category: 'business', aiTool: 'chatgpt', tags: ['persona', 'customer', 'marketing', 'ux'], trendingScore: 88, likeCount: 334 },
  { title: 'Meeting Agenda & Minutes Template', content: `Create a professional meeting structure for:\n\nMeeting type: [TEAM/CLIENT/BOARD/etc.]\nPurpose: [MEETING OBJECTIVE]\nDuration: [LENGTH]\nAttendees: [ROLES/NAMES]\nKey topics: [TOPIC LIST]\n\nProvide:\n1. Pre-meeting agenda template\n2. Facilitation guide with time allocations\n3. Discussion prompts for each topic\n4. Decision-making framework\n5. Meeting minutes template\n6. Action items tracker format\n7. Follow-up email template`, category: 'business', aiTool: 'chatgpt', tags: ['meeting', 'productivity', 'management', 'templates'], trendingScore: 85, likeCount: 298 },
  { title: 'OKR Framework Builder', content: `Help me create quarterly OKRs for [TEAM/COMPANY]:\n\nCompany mission: [MISSION]\nQuarter: [Q1/Q2/Q3/Q4] [YEAR]\nTop priorities: [LIST 2-3]\nCurrent challenges: [CHALLENGES]\n\nCreate:\n- 3 company-level Objectives\n- 3-5 Key Results per Objective (specific, measurable, time-bound)\n- Scoring guidance (0-1.0 scale)\n- Weekly check-in questions\n- Grading rubric\n\nEnsure OKRs are ambitious (70% achievement = success) and aligned top-down.`, category: 'business', aiTool: 'claude', tags: ['okr', 'goals', 'strategy', 'performance'], trendingScore: 87, likeCount: 312 },
  { title: 'Competitor Analysis Framework', content: `Conduct a detailed competitor analysis for [YOUR COMPANY] vs competitors:\n\nYour company: [DESCRIPTION]\nMain competitors: [LIST 3-5]\nIndustry: [INDUSTRY]\nKey differentiators to analyze: [FACTORS]\n\nFor each competitor analyze:\n1. Product/service features comparison matrix\n2. Pricing strategy\n3. Target market and positioning\n4. Marketing channels and messaging\n5. Customer reviews and sentiment\n6. Strengths and weaknesses\n7. Strategic gaps you can exploit\n\nEnd with your recommended positioning strategy.`, category: 'business', aiTool: 'chatgpt', tags: ['competitor', 'analysis', 'strategy', 'market-research'], trendingScore: 91, likeCount: 423 },
  { title: 'Job Description Writer', content: `Write a compelling job description that attracts top talent:\n\nRole: [JOB TITLE]\nCompany: [COMPANY NAME AND BRIEF DESCRIPTION]\nTeam: [TEAM CONTEXT]\nLocation: [LOCATION/REMOTE POLICY]\nSalary range: [RANGE]\n\nInclude:\n- Attention-grabbing opening\n- Role impact statement\n- Day-in-the-life section\n- Responsibilities (use action verbs)\n- Must-have requirements (be specific, not wishful)\n- Nice-to-have skills\n- Benefits and perks\n- Growth opportunities\n- Inclusive language throughout`, category: 'business', aiTool: 'claude', tags: ['hiring', 'hr', 'recruiting', 'job-description'], trendingScore: 86, likeCount: 278 },
  { title: 'Price Increase Email Template', content: `Write a professional email announcing a price increase to existing customers:\n\nProduct/Service: [NAME]\nCurrent price: [PRICE]\nNew price: [NEW PRICE]\nEffective date: [DATE]\nReason: [BRIEF REASON - costs, improvements, etc.]\nWhat customers get: [VALUE ADDITIONS]\n\nTone: Confident, transparent, value-focused\nDo NOT:\n- Over-apologize\n- Be vague about the increase\n- Make promises you can't keep\n\nDO:\n- Lead with value\n- Be specific about what's changing\n- Give adequate notice\n- Include a clear CTA`, category: 'business', aiTool: 'chatgpt', tags: ['email', 'pricing', 'customer-communication'], trendingScore: 84, likeCount: 245 },
  { title: 'Business Risk Assessment', content: `Perform a business risk assessment for [BUSINESS/PROJECT]:\n\nContext: [DESCRIPTION]\nIndustry: [INDUSTRY]\nStage: [STARTUP/GROWTH/MATURE]\nKey activities: [MAIN OPERATIONS]\n\nAnalyze risks across:\n1. Financial risks\n2. Operational risks\n3. Market/competitive risks\n4. Regulatory/compliance risks\n5. Technology risks\n6. Human capital risks\n7. Reputational risks\n\nFor each risk: Rate likelihood (1-5), impact (1-5), current controls, mitigation strategies, and risk owner.`, category: 'business', aiTool: 'claude', tags: ['risk', 'assessment', 'management', 'planning'], trendingScore: 83, likeCount: 234 },

  // EDUCATION (10)
  { title: 'Feynman Technique Explainer', content: `Explain [COMPLEX TOPIC] using the Feynman Technique:\n\n1. Explain it as if teaching a 12-year-old (no jargon)\n2. Use 2-3 concrete, everyday analogies\n3. Identify the 3 most common misconceptions\n4. Highlight what makes this concept truly surprising or counterintuitive\n5. Connect it to something the learner already knows\n6. End with 3 questions that test real understanding (not memorization)\n\nAim for clarity over completeness. If you can't explain it simply, you don't understand it yet.`, category: 'education', aiTool: 'claude', tags: ['learning', 'feynman', 'explanation', 'simplify'], trendingScore: 95, likeCount: 567 },
  { title: 'Study Plan Creator', content: `Create a comprehensive study plan for [SUBJECT/EXAM/SKILL]:\n\nGoal: [WHAT YOU WANT TO ACHIEVE]\nCurrent level: [BEGINNER/INTERMEDIATE/ADVANCED]\nTime available: [HOURS PER DAY] for [NUMBER OF WEEKS]\nLearning style: [VISUAL/AUDITORY/KINESTHETIC/READING]\nExam date (if applicable): [DATE]\n\nProvide:\n- Week-by-week syllabus\n- Daily study schedule template\n- Resource list (books, websites, videos)\n- Practice strategy\n- Review and retention techniques\n- Progress milestones\n- Self-assessment checkpoints`, category: 'education', aiTool: 'chatgpt', tags: ['study', 'learning', 'planning', 'exam'], trendingScore: 91, likeCount: 445 },
  { title: 'Lesson Plan Generator', content: `Create a detailed lesson plan for teaching [TOPIC]:\n\nSubject: [SUBJECT]\nGrade level: [GRADE/AGE]\nDuration: [CLASS LENGTH]\nLearning objectives: [WHAT STUDENTS WILL LEARN]\nPrior knowledge: [WHAT THEY ALREADY KNOW]\n\nInclude:\n- Learning objectives (Bloom's Taxonomy)\n- Materials needed\n- Warm-up activity (5 min)\n- Main instruction (input method)\n- Guided practice\n- Independent practice\n- Formative assessment\n- Closure activity\n- Differentiation strategies for different learners\n- Homework assignment`, category: 'education', aiTool: 'claude', tags: ['lesson-plan', 'teaching', 'curriculum', 'classroom'], trendingScore: 88, likeCount: 378 },
  { title: 'Flashcard Creator Spaced Repetition', content: `Create 20 flashcards for [TOPIC] optimized for spaced repetition learning:\n\nSubject: [SUBJECT]\nLevel: [BEGINNER/INTERMEDIATE/ADVANCED]\nFormat: Q&A pairs\n\nFor each flashcard:\n- Front: Clear, specific question or prompt\n- Back: Concise, memorable answer\n- Mnemonic device where helpful\n- Example or context\n\nOrganize by:\n- Core concepts first\n- Building blocks before complex ideas\n- Include both definition and application questions\n\nTag each card: [concept/application/formula/definition]`, category: 'education', aiTool: 'chatgpt', tags: ['flashcards', 'spaced-repetition', 'memorization', 'anki'], trendingScore: 89, likeCount: 412 },
  { title: 'Socratic Dialogue Tutor', content: `Act as a Socratic tutor helping me understand [TOPIC]. Guide me through discovery learning rather than direct instruction.\n\nMy current understanding: [WHAT I THINK I KNOW]\nMy question: [SPECIFIC QUESTION OR CONFUSION]\n\nUse the Socratic method:\n- Ask probing questions instead of giving answers\n- Help me identify my own assumptions\n- Point out contradictions gently\n- Guide me toward the insight\n- Celebrate when I discover something myself\n\nDon't give me the answer directly. Help me think.`, category: 'education', aiTool: 'claude', tags: ['tutoring', 'socratic', 'learning', 'philosophy'], trendingScore: 86, likeCount: 334 },
  { title: 'Quiz Generator with Explanations', content: `Create a 10-question quiz on [TOPIC] with detailed explanations:\n\nSubject: [SUBJECT]\nDifficulty: [EASY/MEDIUM/HARD]\nQuestion types: Mix of multiple choice, true/false, short answer\n\nFor each question provide:\n1. The question clearly stated\n2. Options A-D (for multiple choice)\n3. Correct answer clearly marked\n4. Explanation (2-3 sentences) of WHY it's correct\n5. Common wrong answer analysis\n6. Related concept to study further\n\nProgress from easier to harder questions.`, category: 'education', aiTool: 'chatgpt', tags: ['quiz', 'assessment', 'learning', 'test'], trendingScore: 87, likeCount: 356 },
  { title: 'Concept Map Builder', content: `Build a comprehensive concept map for [TOPIC]:\n\nMain concept: [CENTRAL TOPIC]\nScope: [BROAD/SPECIFIC]\nAudience: [LEARNER LEVEL]\n\nCreate a hierarchical structure:\n1. Central concept\n2. 4-6 main branches (key subtopics)\n3. 3-4 sub-concepts per branch\n4. Cross-links between related concepts\n5. Examples for abstract concepts\n6. Key questions that link concepts\n\nPresent as a structured outline that could be drawn as a visual map. Use arrows and relationship labels.`, category: 'education', aiTool: 'claude', tags: ['concept-map', 'visual-learning', 'structure', 'mind-map'], trendingScore: 83, likeCount: 267 },
  { title: 'Research Paper Summarizer', content: `Summarize the following research paper for a non-expert audience:\n\n[PASTE PAPER ABSTRACT/FULL TEXT]\n\nProvide:\n1. **What they studied** (1-2 sentences, plain language)\n2. **Why it matters** (real-world significance)\n3. **How they did it** (methodology simplified)\n4. **What they found** (key results, with numbers if important)\n5. **What this means** (implications and applications)\n6. **Limitations** (what they couldn't answer)\n7. **My questions** (3 things worth investigating further)\n\nAvoid jargon. Explain technical terms. Target a smart generalist reader.`, category: 'education', aiTool: 'claude', tags: ['research', 'summary', 'academic', 'science'], trendingScore: 90, likeCount: 389 },
  { title: 'Language Learning Dialogue Practice', content: `Create a realistic dialogue practice for learning [LANGUAGE]:\n\nScenario: [SITUATION - e.g., ordering coffee, job interview, doctor visit]\nMy level: [A1/A2/B1/B2/C1]\nFocus grammar: [GRAMMAR POINT]\nVocabulary theme: [TOPIC]\n\nProvide:\n1. Full dialogue (10-15 exchanges)\n2. Translation for each line\n3. Grammar notes for focus structures\n4. New vocabulary with pronunciation guide\n5. Cultural notes if relevant\n6. Variation exercises (swap words to practice)\n7. Follow-up conversation starters`, category: 'education', aiTool: 'chatgpt', tags: ['language-learning', 'dialogue', 'practice', 'esl'], trendingScore: 85, likeCount: 312 },
  { title: 'Teaching Analogy Generator', content: `Generate 5 powerful analogies to explain [COMPLEX CONCEPT]:\n\nConcept: [WHAT YOU'RE EXPLAINING]\nAudience: [WHO YOU'RE TEACHING]\nTheir background: [WHAT THEY'RE FAMILIAR WITH]\n\nFor each analogy:\n1. The analogy explained clearly\n2. What maps to what (correspondence table)\n3. Where the analogy breaks down (limitations)\n4. How to use it in teaching (exact words)\n5. A follow-up question to check understanding\n\nPrioritize analogies from everyday life: cooking, sports, music, relationships, nature.`, category: 'education', aiTool: 'claude', tags: ['teaching', 'analogy', 'explanation', 'pedagogy'], trendingScore: 84, likeCount: 289 },

  // MARKETING (10)
  { title: 'Facebook Ad Copy Generator', content: `Write high-converting Facebook ad copy for [PRODUCT/SERVICE]:\n\nProduct: [NAME]\nTarget audience: [DEMOGRAPHICS + INTERESTS]\nMain benefit: [TOP VALUE PROPOSITION]\nOffer: [WHAT YOU'RE PROMOTING]\nBudget indicator: [FREE/UNDER $X/PREMIUM]\nGoal: [AWARENESS/LEADS/SALES]\n\nCreate 3 variations:\n1. Problem-aware ad (leads with pain point)\n2. Solution-aware ad (leads with your product)\n3. Social proof ad (leads with results/testimonial)\n\nFor each: Headline (6 words max), Primary text (125 chars), Description, CTA button. Include emoji where appropriate.`, category: 'marketing', aiTool: 'chatgpt', tags: ['facebook-ads', 'paid-ads', 'copywriting', 'digital-marketing'], trendingScore: 93, likeCount: 534 },
  { title: 'SEO Content Strategy Builder', content: `Build a 6-month SEO content strategy for [WEBSITE/BUSINESS]:\n\nNiche: [YOUR NICHE]\nTarget keywords: [SEED KEYWORDS]\nContent team size: [SOLO/SMALL/LARGE]\nCurrent DA: [DOMAIN AUTHORITY]\nGoal: [TRAFFIC/LEADS/REVENUE]\n\nProvide:\n1. Keyword research framework\n2. Content pillar structure (3-5 pillars)\n3. Monthly content calendar template\n4. Blog post topic ideas (20 topics)\n5. Content types mix (how-to/listicle/case study/etc.)\n6. Internal linking strategy\n7. On-page SEO checklist\n8. Success metrics to track`, category: 'marketing', aiTool: 'claude', tags: ['seo', 'content-strategy', 'organic', 'blogging'], trendingScore: 94, likeCount: 567 },
  { title: 'Email Marketing Sequence', content: `Write a 7-email welcome sequence for new subscribers to [BUSINESS TYPE]:\n\nBusiness: [DESCRIPTION]\nFreebie delivered: [LEAD MAGNET]\nEnd goal: [SELL PRODUCT/BOOK CALL/etc.]\nBrand voice: [PROFESSIONAL/CONVERSATIONAL/FUN]\n\nEmail sequence:\n1. Welcome + deliver freebie\n2. Your story (build connection)\n3. Biggest pain point + insight\n4. Case study/testimonial\n5. Common objections addressed\n6. Product soft mention\n7. Direct offer\n\nFor each email: Subject line (+ A/B test variant), Preview text, Body copy, CTA`, category: 'marketing', aiTool: 'claude', tags: ['email-marketing', 'automation', 'nurture', 'sequence'], trendingScore: 91, likeCount: 456 },
  { title: 'Brand Voice Guide Creator', content: `Create a comprehensive brand voice guide for [BRAND NAME]:\n\nBrand: [NAME]\nIndustry: [INDUSTRY]\nTarget audience: [WHO YOU SERVE]\nBrand values: [3-5 VALUES]\nCompetitor voices to differentiate from: [COMPETITORS]\n\nDefine:\n1. Voice characteristics (4 adjectives + explanation)\n2. Tone variations (social/formal/crisis)\n3. Do's and Don'ts word list\n4. Before/after examples (10 rewrites)\n5. Emoji and punctuation guidelines\n6. How to talk about competitors\n7. Sensitive topic guidelines\n8. Sample copy for 5 scenarios`, category: 'marketing', aiTool: 'chatgpt', tags: ['brand-voice', 'brand-guidelines', 'copywriting', 'branding'], trendingScore: 88, likeCount: 378 },
  { title: 'Instagram Caption Writer', content: `Write 5 Instagram caption variations for [CONTENT TYPE]:\n\nPost topic: [WHAT THE IMAGE/VIDEO SHOWS]\nBusiness: [YOUR BUSINESS TYPE]\nAudience: [YOUR FOLLOWERS]\nGoal: [ENGAGEMENT/WEBSITE CLICKS/BRAND AWARENESS]\nBrand voice: [CASUAL/PROFESSIONAL/INSPIRATIONAL]\n\nFor each caption:\n- Hook first line (stops the scroll)\n- Value/story in the body\n- CTA that feels natural\n- 10-15 relevant hashtags (mix of sizes)\n- Strategic emoji placement\n\nVary the style: storytelling, educational, humor, inspiration, question.`, category: 'marketing', aiTool: 'chatgpt', tags: ['instagram', 'social-media', 'captions', 'hashtags'], trendingScore: 89, likeCount: 412 },
  { title: 'Cold Email Outreach Template', content: `Write a cold email outreach sequence that gets replies:\n\nYou are: [YOUR ROLE]\nOutreaching to: [TARGET ROLE/COMPANY TYPE]\nYour offer: [WHAT YOU PROVIDE]\nKey pain point you solve: [THE PROBLEM]\nSocial proof: [RELEVANT CREDENTIAL]\n\nCreate:\n1. Initial email (under 100 words)\n2. Follow-up #1 (Day 3 — add value)\n3. Follow-up #2 (Day 7 — different angle)\n4. Break-up email (Day 14)\n\nFor each: Subject line, body, CTA. Keep it personal, specific to their business, and not salesy.`, category: 'marketing', aiTool: 'claude', tags: ['cold-email', 'outreach', 'b2b', 'sales'], trendingScore: 90, likeCount: 445 },
  { title: 'Marketing Campaign Planner', content: `Plan a complete marketing campaign for [PRODUCT LAUNCH/PROMOTION]:\n\nProduct: [NAME]\nCampaign goal: [OBJECTIVE + KPIs]\nBudget: [AMOUNT]\nDuration: [TIMEFRAME]\nTarget audience: [DEMOGRAPHICS]\nChannels available: [LIST YOUR CHANNELS]\n\nProvide:\n1. Campaign theme and messaging\n2. Channel strategy with budget allocation\n3. Week-by-week content calendar\n4. Key messages per audience segment\n5. Creative brief for visual assets\n6. Launch sequence (pre/during/post)\n7. Tracking and attribution plan\n8. Success metrics and reporting cadence`, category: 'marketing', aiTool: 'chatgpt', tags: ['campaign', 'planning', 'launch', 'strategy'], trendingScore: 87, likeCount: 334 },
  { title: 'Customer Testimonial Optimizer', content: `Transform a rough customer testimonial into compelling social proof:\n\nRaw testimonial: [PASTE ORIGINAL TESTIMONIAL]\nProduct/Service used: [NAME]\nCustomer type: [B2B/B2C, brief description]\nWhere it will be used: [WEBSITE/AD/CASE STUDY]\n\nOptimize for:\n1. Lead with specific result (numbers preferred)\n2. Include before/after contrast\n3. Address the main objection\n4. Sound authentic (not corporate)\n5. End with recommendation\n\nAlso provide:\n- Short version (25 words for ad copy)\n- Pull quote for website hero\n- Key stats to highlight`, category: 'marketing', aiTool: 'claude', tags: ['testimonial', 'social-proof', 'conversion', 'trust'], trendingScore: 85, likeCount: 289 },
  { title: 'TikTok/Reels Video Script', content: `Write a viral TikTok/Reels script about [TOPIC]:\n\nNiche: [YOUR NICHE]\nVideo length: [15/30/60/90 seconds]\nHook type: [BOLD CLAIM/QUESTION/SURPRISING FACT/STORY]\nContent format: [TUTORIAL/LIST/STORYTIME/POV]\n\nScript format:\n- [0-3s] HOOK: Say exactly this first sentence...\n- [3-10s] CONTEXT: Brief setup...\n- [10-45s] MAIN CONTENT: Step by step...\n- [45-55s] PAYOFF: The satisfying conclusion...\n- [55-60s] CTA: What to do next...\n\nInclude camera directions, text overlay suggestions, trending audio notes.`, category: 'marketing', aiTool: 'chatgpt', tags: ['tiktok', 'reels', 'video', 'viral', 'script'], trendingScore: 92, likeCount: 512 },
  { title: 'Landing Page Conversion Copy', content: `Write high-converting landing page copy for [PRODUCT/SERVICE]:\n\nOffer: [WHAT YOU'RE SELLING]\nPrice: [PRICE POINT]\nTarget: [IDEAL CUSTOMER]\nMain objection: [BIGGEST HESITATION]\nTop 3 benefits: [LIST THEM]\nSocial proof available: [WHAT YOU HAVE]\n\nSections to write:\n1. Hero headline + subheadline\n2. Problem section (agitate the pain)\n3. Solution introduction\n4. Features to benefits section (5 items)\n5. Social proof block\n6. FAQ (5 objection-based questions)\n7. Final CTA with urgency element\n\nOptimize for a conversion rate of 3-5%.`, category: 'marketing', aiTool: 'claude', tags: ['landing-page', 'conversion', 'copywriting', 'sales-page'], trendingScore: 96, likeCount: 623 },

  // CREATIVE (10)
  { title: 'World Building Framework', content: `Help me build a rich fictional world for [GENRE] story:\n\nGenre: [FANTASY/SCI-FI/DYSTOPIAN/etc.]\nCore concept: [THE BIG IDEA OF YOUR WORLD]\nTime period: [ERA]\nTone: [DARK/HOPEFUL/SATIRICAL/EPIC]\n\nDevelop:\n1. Geography and climate\n2. Political systems and power structures\n3. Economic systems and trade\n4. Cultural norms, religion, beliefs\n5. Magic system / technology (rules and limitations)\n6. History (the 5 key events that shaped this world)\n7. Factions in conflict\n8. Daily life for common people\n9. Unique details that make it memorable`, category: 'creative', aiTool: 'claude', tags: ['worldbuilding', 'fiction', 'fantasy', 'writing'], trendingScore: 93, likeCount: 478 },
  { title: 'Character Development Deep Dive', content: `Create a fully-developed character for my [GENRE] story:\n\nRole in story: [PROTAGONIST/ANTAGONIST/SUPPORTING]\nGender/Age: [DETAILS]\nSetting/World: [BRIEF CONTEXT]\nCore conflict: [WHAT DRIVES THE STORY]\n\nDevelop:\n1. Backstory (formative events)\n2. Core wound and resulting belief\n3. External goal (what they want)\n4. Internal goal (what they need)\n5. Fatal flaw\n6. Greatest strength\n7. Voice and speech patterns\n8. Physical description (distinctive features)\n9. Relationships and dynamics\n10. Character arc (where they start vs. end)\n11. 3 signature scenes that reveal character`, category: 'creative', aiTool: 'claude', tags: ['character', 'fiction', 'writing', 'storytelling'], trendingScore: 90, likeCount: 412 },
  { title: 'Poem Generator with Emotion', content: `Write a poem about [SUBJECT] that captures [EMOTION]:\n\nTheme: [MAIN THEME]\nEmotion to evoke: [SPECIFIC FEELING]\nStyle: [FREE VERSE/HAIKU/SONNET/VILLANELLE/etc.]\nLength: [SHORT/MEDIUM/LONG]\nMood: [MELANCHOLIC/JOYFUL/CONTEMPLATIVE/etc.]\nImagery preference: [NATURE/URBAN/ABSTRACT]\n\nRequirements:\n- Original metaphors (avoid clichés)\n- Sensory details that transport the reader\n- Rhythm that feels natural when read aloud\n- A surprising image or twist\n- Emotional resonance in the final lines\n\nWrite the poem, then explain the creative choices made.`, category: 'creative', aiTool: 'claude', tags: ['poetry', 'creative-writing', 'emotion', 'literature'], trendingScore: 88, likeCount: 367 },
  { title: 'Plot Twist Generator', content: `Generate 10 unexpected plot twists for my story:\n\nGenre: [GENRE]\nCurrent story setup: [BRIEF SUMMARY]\nMain characters: [CHARACTER NAMES AND ROLES]\nTheme: [CENTRAL THEME]\nTone: [SERIOUS/COMEDIC/THRILLER]\n\nFor each twist:\n1. The twist itself\n2. The setup clues that could be planted earlier (retroactive foreshadowing)\n3. Character impact (how it changes motivations)\n4. Plot consequences\n5. Emotional impact on reader\n\nRate each twist: Predictability score (1-10), emotional impact (1-10), complexity to execute (1-10).`, category: 'creative', aiTool: 'chatgpt', tags: ['plot-twist', 'storytelling', 'fiction', 'writing'], trendingScore: 91, likeCount: 445 },
  { title: 'Song Lyrics Writer', content: `Write original song lyrics for [GENRE] about [TOPIC]:\n\nGenre: [GENRE - pop/indie/hip-hop/country/etc.]\nMood: [UPBEAT/SAD/ANGRY/NOSTALGIC]\nTheme: [MAIN SUBJECT OR STORY]\nPersonal element: [SPECIFIC DETAIL TO INCLUDE]\nStructure: Verse-Chorus-Verse-Chorus-Bridge-Chorus\n\nRequirements:\n- Hook in the chorus that repeats memorably\n- Specific, visual imagery (avoid generic phrases)\n- Emotional authenticity\n- Rhyme scheme that feels natural, not forced\n- Bridge that shifts perspective or escalates\n- Lines that scan well to a rhythm\n\nProvide notes on possible melodic approach.`, category: 'creative', aiTool: 'claude', tags: ['songwriting', 'lyrics', 'music', 'creative'], trendingScore: 89, likeCount: 389 },
  { title: 'Screenplay Scene Writer', content: `Write a professional screenplay scene:\n\nGenre: [GENRE]\nLocation: [INT./EXT. LOCATION - DAY/NIGHT]\nCharacters: [LIST WITH BRIEF DESCRIPTION]\nScene objective: [WHAT MUST HAPPEN IN THIS SCENE]\nSubtext: [WHAT'S REALLY GOING ON BENEATH THE SURFACE]\nTone: [TENSE/COMEDIC/EMOTIONAL/ACTION]\n\nFormat properly with:\n- Scene heading\n- Action lines (show, don't tell)\n- Character names centered above dialogue\n- Dialogue with distinct voices\n- Parentheticals only when essential\n\nLength: 2-3 pages (approx. 2-3 minutes of screen time)`, category: 'creative', aiTool: 'chatgpt', tags: ['screenplay', 'script', 'film', 'dialogue'], trendingScore: 86, likeCount: 312 },
  { title: 'Mythology Creator', content: `Create an original myth or legend for [WORLD/CULTURE]:\n\nCulture/Setting: [CIVILIZATION DESCRIPTION]\nWhat to explain: [NATURAL PHENOMENON/CULTURAL PRACTICE/MORAL LESSON]\nGods/Spirits involved: [PANTHEON DETAILS]\nHero or protagonist: [CHARACTER]\nMoral or lesson: [THEME]\n\nStructure as a traditional myth:\n1. The world before (context)\n2. The inciting event\n3. The quest or challenge\n4. Divine intervention and tests\n5. Climax and resolution\n6. How the world changed as a result\n7. The lesson passed down through generations\n\nUse elevated, timeless language. Include at least one transformation.`, category: 'creative', aiTool: 'claude', tags: ['mythology', 'worldbuilding', 'fantasy', 'legend'], trendingScore: 85, likeCount: 289 },
  { title: 'Comedy Sketch Writer', content: `Write a comedic sketch about [TOPIC]:\n\nFormat: [TWO-PERSON DIALOGUE/MONOLOGUE/ENSEMBLE]\nLength: [2-3 MINUTES]\nStyle: [ABSURDIST/SATIRICAL/OBSERVATIONAL/PARODY]\nSetting: [LOCATION]\nComedy target: [WHAT YOU'RE POKING FUN AT]\n\nRequirements:\n- Strong setup in first 30 seconds\n- Escalating absurdity\n- A signature catchphrase or repeated element\n- Subverted expectation at least twice\n- Punchy ending that lands the biggest laugh\n- Stage directions for physical comedy\n\nInclude performance notes for timing and delivery.`, category: 'creative', aiTool: 'chatgpt', tags: ['comedy', 'sketch', 'humor', 'script'], trendingScore: 83, likeCount: 267 },
  { title: 'Game Narrative Designer', content: `Design the narrative for a [GAME TYPE] game:\n\nGenre: [RPG/ADVENTURE/HORROR/etc.]\nSetting: [WORLD DESCRIPTION]\nPlayer character: [PROTAGONIST ROLE]\nCore conflict: [MAIN ANTAGONIST/CHALLENGE]\nTheme: [CENTRAL MESSAGE]\nTone: [DARK/EPIC/WHIMSICAL]\n\nProvide:\n1. Main story arc (3-act structure)\n2. 5 major story beats\n3. Main character backstory\n4. 3 faction descriptions\n5. 10 side quest hooks\n6. World lore fragment (in-world document)\n7. Key NPC character sketches (5)\n8. Branching narrative decision point`, category: 'creative', aiTool: 'claude', tags: ['game-design', 'narrative', 'rpg', 'storytelling'], trendingScore: 92, likeCount: 456 },
  { title: 'Creative Prompt Chain', content: `Start a collaborative creative story with me using this setup:\n\n[WRITE YOUR OPENING PARAGRAPH HERE]\n\nRules for our collaboration:\n- Continue my story naturally, matching the tone and style\n- Add one unexpected element each turn\n- Never resolve the main tension too quickly\n- Every paragraph should end with an implicit question or tension\n- After 4 exchanges, suggest a dramatic turning point\n\nPick up exactly where I left off and continue for 2-3 paragraphs. Then pause and wait for my continuation.`, category: 'creative', aiTool: 'claude', tags: ['collaborative', 'fiction', 'story', 'creative-writing'], trendingScore: 84, likeCount: 312 },

  // PRODUCTIVITY (10)
  { title: 'Daily Planning System', content: `Create my optimal daily plan for maximum productivity:\n\nMy role: [JOB TITLE]\nTop priorities today: [LIST 3-5]\nEnergy peaks: [MORNING/AFTERNOON/EVENING person]\nCommitments: [MEETINGS OR FIXED EVENTS]\nCurrent biggest blocker: [WHAT'S STOPPING YOU]\n\nCreate:\n1. Morning routine (first 60 min)\n2. Time-blocked schedule for deep work\n3. Task batching strategy\n4. Email/Slack response windows\n5. Energy management tips\n6. Evening shutdown routine\n7. Decision: what to delegate or defer\n\nOptimize for: [DEEP WORK/CREATIVE OUTPUT/MEETINGS/ADMIN]`, category: 'productivity', aiTool: 'chatgpt', tags: ['daily-planning', 'time-management', 'productivity', 'schedule'], trendingScore: 92, likeCount: 489 },
  { title: 'Decision Making Framework', content: `Help me make a difficult decision about [DECISION TO MAKE]:\n\nOptions:\n1. [OPTION A]\n2. [OPTION B]\n3. [OPTION C if applicable]\n\nContext: [RELEVANT BACKGROUND]\nTimeframe: [WHEN DO YOU NEED TO DECIDE]\nStakeholders affected: [WHO IS IMPACTED]\nYour values: [WHAT MATTERS MOST TO YOU]\n\nAnalyze using:\n1. 10/10/10 rule (impact in 10 min/10 months/10 years)\n2. Regret minimization framework\n3. Second-order consequences\n4. Risk assessment for each option\n5. Reversibility check\n\nEnd with: a recommendation and the one question I should ask myself.`, category: 'productivity', aiTool: 'claude', tags: ['decision-making', 'strategy', 'frameworks', 'thinking'], trendingScore: 90, likeCount: 423 },
  { title: 'Meeting Summarizer & Action Items', content: `Transform these meeting notes into a clean summary:\n\n[PASTE MEETING NOTES OR TRANSCRIPT]\n\nMeeting type: [TYPE]\nDate: [DATE]\nAttendees: [LIST]\n\nOrganize into:\n## Summary\nOne paragraph overview of what was discussed and decided.\n\n## Key Decisions\nBulleted list of decisions made.\n\n## Action Items\n| Owner | Task | Deadline | Priority |\n|-------|------|----------|----------|\n\n## Open Questions\nUnresolved items needing follow-up.\n\n## Next Meeting\nDate, agenda preview.\n\nKeep each section concise and scannable.`, category: 'productivity', aiTool: 'claude', tags: ['meetings', 'notes', 'action-items', 'summary'], trendingScore: 93, likeCount: 512 },
  { title: 'Inbox Zero Email System', content: `Create a personalized email management system to reach Inbox Zero:\n\nMy email volume: [EMAILS/DAY]\nRoles/senders I get email from: [LIST]\nEmail client: [GMAIL/OUTLOOK/etc.]\nTime I want to spend on email: [MINUTES/DAY]\nBiggest email problems: [DESCRIBE]\n\nProvide:\n1. Folder/label structure\n2. Filter rules to set up (specific examples)\n3. Triage framework (4D method adapted)\n4. Template library (10 common email replies)\n5. Two email sessions schedule\n6. Unsubscribe strategy\n7. Weekly email maintenance routine\n8. How to handle urgent/non-urgent distinction`, category: 'productivity', aiTool: 'chatgpt', tags: ['email', 'inbox-zero', 'organization', 'efficiency'], trendingScore: 87, likeCount: 356 },
  { title: 'Note-Taking System Builder', content: `Design a personal knowledge management system for [USE CASE]:\n\nPurpose: [WORK/STUDY/PERSONAL/CREATIVE]\nCurrent problem: [WHAT'S NOT WORKING]\nTools available: [NOTION/OBSIDIAN/ROAM/APPLE NOTES/etc.]\nVolume: [HOW MUCH DO YOU NOTE DAILY]\nGoal: [WHAT SHOULD YOUR NOTES ENABLE]\n\nDesign:\n1. Capture method (quick notes)\n2. Folder/tag structure\n3. Templates for recurring note types\n4. Review and processing schedule\n5. Linking/connecting notes strategy\n6. Archiving rules\n7. Weekly/monthly review process\n8. Search and retrieval approach`, category: 'productivity', aiTool: 'claude', tags: ['note-taking', 'pkm', 'knowledge-management', 'second-brain'], trendingScore: 89, likeCount: 398 },
  { title: 'Goal Setting SMART+ Framework', content: `Help me create powerful goals using an enhanced SMART framework:\n\nLife area: [CAREER/HEALTH/RELATIONSHIPS/FINANCES/etc.]\nBig dream: [YOUR AMBITIOUS GOAL]\nTimeframe: [ANNUAL/QUARTERLY/MONTHLY]\nCurrent situation: [WHERE YOU ARE NOW]\nResources: [TIME/MONEY/SUPPORT AVAILABLE]\nPrevious attempts: [WHAT YOU'VE TRIED]\n\nCreate:\n1. SMART goal statement\n2. Identity statement (who you need to become)\n3. 90-day milestone\n4. 30-day action plan\n5. Weekly non-negotiable habits\n6. Obstacle anticipation (if-then planning)\n7. Accountability structure\n8. Progress tracking method`, category: 'productivity', aiTool: 'chatgpt', tags: ['goals', 'smart-goals', 'planning', 'habits'], trendingScore: 91, likeCount: 467 },
  { title: 'Delegation Decision Helper', content: `Help me decide what to delegate from my task list:\n\nMy role: [YOUR POSITION]\nTeam/resources available: [WHO CAN HELP]\nHourly value of my time: [$AMOUNT]\nTask list:\n[PASTE YOUR TASK LIST]\n\nFor each task analyze:\n1. Could someone else do this at 80%+ quality?\n2. Does this require my specific expertise?\n3. What's the cost of delegating vs doing it myself?\n4. Training time required\n5. Delegation risk level\n\nOutput as a matrix: Do/Delegate/Delete/Defer\nInclude delegation brief template for top 3 items to hand off.`, category: 'productivity', aiTool: 'claude', tags: ['delegation', 'management', 'leadership', 'efficiency'], trendingScore: 85, likeCount: 312 },
  { title: 'Personal SOP Creator', content: `Create a Standard Operating Procedure (SOP) for: [RECURRING TASK]\n\nTask description: [WHAT IT IS]\nFrequency: [HOW OFTEN]\nTime required: [DURATION]\nTools used: [SOFTWARE/TOOLS]\nCurrent pain points: [WHAT GOES WRONG]\n\nSOP format:\n1. Purpose and scope\n2. Prerequisites (what you need before starting)\n3. Step-by-step instructions (numbered, specific)\n4. Decision points and troubleshooting\n5. Quality check checklist\n6. Common mistakes to avoid\n7. Time estimates per step\n8. Links to resources/templates\n\nMake it so detailed that someone unfamiliar could follow it perfectly.`, category: 'productivity', aiTool: 'chatgpt', tags: ['sop', 'systems', 'process', 'automation'], trendingScore: 86, likeCount: 334 },
  { title: 'Brain Dump Organizer', content: `I have a brain dump of everything on my mind. Help me organize it:\n\n[PASTE YOUR BRAIN DUMP - everything you're thinking about, worrying about, need to do, want to do, random thoughts, etc.]\n\nOrganize into:\n1. **Immediate actions** (do this week)\n2. **Projects** (multi-step goals, needs planning)\n3. **Someday/Maybe** (ideas to revisit)\n4. **Worries to process** (anxiety, needs reflection)\n5. **Reference info** (save somewhere)\n6. **Delegate** (give to someone)\n7. **Delete** (not worth keeping)\n\nThen: Identify my top 3 priorities from the immediate actions list and help me schedule them.`, category: 'productivity', aiTool: 'claude', tags: ['brain-dump', 'gtd', 'organization', 'clarity'], trendingScore: 88, likeCount: 378 },
  { title: 'Weekly Review Template', content: `Guide me through a comprehensive weekly review:\n\nWeek of: [DATE RANGE]\nRole/Context: [BRIEF DESCRIPTION]\n\nReview these areas:\n\n**LAST WEEK ASSESSMENT**\n- What went well? (Celebrate wins)\n- What didn't go as planned? (Lessons)\n- Energy levels throughout the week?\n- Did I move toward my top goals?\n\n**CAPTURE & CLARIFY**\n- What's still on my mind?\n- Open loops to close?\n- Commitments made?\n\n**NEXT WEEK PLANNING**\n- Top 3 priorities\n- Must-do tasks by Friday\n- Challenging situation to prepare for\n- One habit to focus on\n\nAsk me questions to help me think through each section.`, category: 'productivity', aiTool: 'chatgpt', tags: ['weekly-review', 'reflection', 'gtd', 'planning'], trendingScore: 84, likeCount: 289 },

  // RESEARCH (10)
  { title: 'Research Question Refiner', content: `Help me develop a strong research question from my broad interest:\n\nBroad topic: [YOUR TOPIC]\nField: [ACADEMIC FIELD]\nYour angle/interest: [WHAT SPECIFICALLY INTERESTS YOU]\nAudience: [WHO WILL READ THIS]\nScope: [PAPER LENGTH/RESEARCH DURATION]\n\nHelp me:\n1. Narrow from broad to specific\n2. Identify 3-5 viable research questions\n3. Test each for: feasibility, significance, novelty\n4. Suggest the strongest question\n5. Develop sub-questions\n6. Identify potential thesis statement\n7. Map key search terms for literature review\n8. Flag potential methodological approaches`, category: 'research', aiTool: 'claude', tags: ['research', 'academic', 'methodology', 'thesis'], trendingScore: 88, likeCount: 367 },
  { title: 'Literature Review Synthesizer', content: `Synthesize these research papers into a coherent literature review section:\n\nTopic: [YOUR RESEARCH TOPIC]\nPapers to synthesize:\n1. [PAPER 1 TITLE + MAIN FINDING]\n2. [PAPER 2 TITLE + MAIN FINDING]\n3. [PAPER 3 TITLE + MAIN FINDING]\n(Add more as needed)\n\nCreate a literature review that:\n- Groups papers thematically (not chronologically)\n- Identifies agreements and contradictions\n- Shows how each paper relates to your research\n- Identifies gaps your research addresses\n- Uses proper academic voice\n- Includes transition sentences between ideas\n\nAim for [LENGTH] and use [CITATION STYLE].`, category: 'research', aiTool: 'claude', tags: ['literature-review', 'academic', 'synthesis', 'research'], trendingScore: 90, likeCount: 412 },
  { title: 'Fact-Checker and Source Evaluator', content: `Help me evaluate the credibility and accuracy of this claim:\n\nClaim: [PASTE THE CLAIM OR ARTICLE]\nSource: [WHERE IT CAME FROM]\nContext: [WHERE YOU ENCOUNTERED IT]\n\nAnalyze:\n1. Is this claim verifiable? What evidence would confirm/deny it?\n2. What are the key assumptions being made?\n3. What context might be missing?\n4. Identify potential bias in the source\n5. What are the strongest counterarguments?\n6. What would a skeptic say?\n7. Rate credibility: [1-10] with reasoning\n8. Recommend authoritative sources to verify\n\nBe balanced — don't dismiss or uncritically accept.`, category: 'research', aiTool: 'claude', tags: ['fact-checking', 'critical-thinking', 'media-literacy', 'research'], trendingScore: 92, likeCount: 456 },
  { title: 'Interview Question Generator', content: `Generate comprehensive interview questions for researching [TOPIC]:\n\nResearch purpose: [WHAT YOU'RE STUDYING]\nInterviewee profile: [WHO YOU'RE INTERVIEWING]\nResearch questions: [WHAT YOU WANT TO UNDERSTAND]\nInterview type: [STRUCTURED/SEMI-STRUCTURED]\nDuration: [TIME AVAILABLE]\n\nCreate:\n1. Warm-up questions (2-3)\n2. Core questions (8-10) with probing follow-ups\n3. Hypothetical scenarios (2-3)\n4. Sensitive topic questions (handle with care)\n5. Closing questions\n\nFor each question:\n- Why you're asking it\n- What a good answer reveals\n- Red flags to watch for\n- Probing follow-ups if answer is vague`, category: 'research', aiTool: 'chatgpt', tags: ['interview', 'qualitative-research', 'methodology', 'questions'], trendingScore: 85, likeCount: 312 },
  { title: 'Data Analysis Interpretation Helper', content: `Help me interpret this data and extract meaningful insights:\n\nData type: [SURVEY RESULTS/SALES DATA/EXPERIMENT RESULTS/etc.]\nContext: [WHAT YOU'RE STUDYING]\nData summary: [PASTE KEY NUMBERS OR RESULTS]\nHypothesis: [WHAT YOU EXPECTED TO FIND]\n\nAnalyze:\n1. Key patterns and trends\n2. Surprising or unexpected findings\n3. Statistical significance considerations\n4. Correlation vs causation distinctions\n5. Confounding variables to consider\n6. Limitations of this data\n7. What additional data would strengthen conclusions\n8. How to visualize this data effectively\n9. Recommended conclusions\n10. Next steps for research`, category: 'research', aiTool: 'claude', tags: ['data-analysis', 'statistics', 'research', 'insights'], trendingScore: 91, likeCount: 423 },
  { title: 'Systematic Review Framework', content: `Help me design a systematic literature review on [TOPIC]:\n\nResearch question: [YOUR QUESTION]\nField: [ACADEMIC DISCIPLINE]\nDaterange: [YEARS TO SEARCH]\nLanguages: [ENGLISH/MULTILINGUAL]\n\nProvide:\n1. PRISMA flow diagram structure\n2. Inclusion/exclusion criteria\n3. Database search strategy (PubMed, Scopus, Web of Science)\n4. Search strings with Boolean operators\n5. Quality assessment checklist\n6. Data extraction template\n7. Synthesis approach (narrative/meta-analysis)\n8. Bias assessment framework\n9. Reporting guidelines to follow`, category: 'research', aiTool: 'claude', tags: ['systematic-review', 'meta-analysis', 'academic', 'methodology'], trendingScore: 86, likeCount: 298 },
  { title: 'Survey Design Expert', content: `Design a research survey for studying [RESEARCH TOPIC]:\n\nPurpose: [WHAT YOU WANT TO LEARN]\nTarget respondents: [WHO WILL ANSWER]\nExpected sample size: [NUMBER]\nDelivery method: [ONLINE/IN-PERSON/PHONE]\nTime to complete: [MINUTES]\n\nCreate:\n1. Survey structure and flow\n2. 15-20 questions covering:\n   - Demographic filters\n   - Behavioral questions\n   - Attitudinal questions (Likert scales)\n   - Open-ended questions\n3. Question wording review (avoid bias)\n4. Skip logic recommendations\n5. Pilot testing checklist\n6. Response rate optimization tips\n7. Analysis plan for each question type`, category: 'research', aiTool: 'chatgpt', tags: ['survey', 'research-methods', 'data-collection', 'questionnaire'], trendingScore: 84, likeCount: 278 },
  { title: 'Secondary Research Synthesizer', content: `I need to understand [TOPIC] quickly using secondary research. Act as my research assistant.\n\nTopic: [SPECIFIC TOPIC]\nPurpose: [WHY YOU NEED THIS]\nDepth needed: [OVERVIEW/DETAILED]\nTime: [HOW CURRENT MUST IT BE]\n\nProvide:\n1. Key concepts I need to understand\n2. Historical context and development\n3. Current state of knowledge\n4. Major debates or controversies\n5. Key players (researchers/organizations/companies)\n6. Best resources for each depth level:\n   - Quick overview (articles, videos)\n   - Deeper dive (books, papers)\n   - Expert-level (journals, conferences)\n7. Glossary of essential terms\n8. Questions that remain unanswered`, category: 'research', aiTool: 'perplexity', tags: ['secondary-research', 'overview', 'synthesis', 'learning'], trendingScore: 89, likeCount: 389 },
  { title: 'Hypothesis Generator', content: `Help me develop testable hypotheses for my research:\n\nResearch area: [FIELD/TOPIC]\nObservation: [WHAT YOU'VE NOTICED OR QUESTION YOU HAVE]\nExisting theory: [RELEVANT THEORY OR FRAMEWORK]\nVariables of interest: [INDEPENDENT/DEPENDENT VARIABLES]\n\nFor each hypothesis:\n1. Null hypothesis (H₀)\n2. Alternative hypothesis (H₁)\n3. Directional vs non-directional consideration\n4. Testability assessment\n5. Measurement approach\n6. Potential confounds\n7. Effect size estimation\n8. Sample size considerations\n\nGenerate 3-5 hypotheses ranging from conservative to bold.`, category: 'research', aiTool: 'claude', tags: ['hypothesis', 'scientific-method', 'research-design', 'statistics'], trendingScore: 83, likeCount: 256 },
  { title: 'Expert Source Finder', content: `Help me identify the best sources and experts on [TOPIC]:\n\nTopic: [SPECIFIC SUBJECT]\nPurpose: [JOURNALISM/ACADEMIC/PROFESSIONAL/PERSONAL]\nDepth needed: [SURFACE/MODERATE/EXPERT]\nRecency required: [CURRENT/HISTORICAL PERSPECTIVE OK]\n\nFind:\n1. Leading academic researchers (+ their institutions)\n2. Key practitioners in the field\n3. Best peer-reviewed journals\n4. Most cited/foundational papers\n5. Industry reports and databases\n6. Quality YouTube channels/podcasts\n7. Communities/forums where experts gather\n8. Contrarian voices worth considering\n9. Red flag sources to avoid and why\n10. Questions to ask to identify true experts`, category: 'research', aiTool: 'perplexity', tags: ['sources', 'experts', 'research', 'verification'], trendingScore: 87, likeCount: 334 },

  // ANALYSIS (10)
  { title: 'Porter Five Forces Analysis', content: `Conduct a Porter's Five Forces analysis for [INDUSTRY/COMPANY]:\n\nIndustry: [INDUSTRY]\nFocus company: [COMPANY NAME (optional)]\nGeography: [MARKET]\nTime horizon: [CURRENT/5-YEAR OUTLOOK]\n\nFor each force rate intensity (Low/Medium/High) and explain:\n1. **Competitive Rivalry**: Number of competitors, differentiation, switching costs\n2. **Threat of New Entrants**: Barriers to entry, capital requirements, regulations\n3. **Supplier Power**: Concentration, switching costs, forward integration threat\n4. **Buyer Power**: Concentration, price sensitivity, backward integration threat\n5. **Threat of Substitutes**: Available alternatives, switching costs, performance\n\nEnd with: Overall industry attractiveness score and strategic implications.`, category: 'analysis', aiTool: 'claude', tags: ['porter', 'competitive-analysis', 'strategy', 'business'], trendingScore: 91, likeCount: 445 },
  { title: 'Financial Statement Analyzer', content: `Analyze the following financial data and extract insights:\n\nCompany: [COMPANY NAME]\nPeriod: [QUARTER/YEAR]\nData provided: [INCOME STATEMENT/BALANCE SHEET/CASH FLOW]\n\n[PASTE FINANCIAL DATA]\n\nAnalyze:\n1. Revenue growth trends\n2. Profitability ratios (gross/operating/net margin)\n3. Liquidity ratios (current, quick)\n4. Efficiency ratios (asset turnover, inventory days)\n5. Leverage ratios (debt-to-equity, interest coverage)\n6. Cash flow quality\n7. Year-over-year changes (flag anomalies)\n8. Red flags or concerns\n9. Comparison to industry benchmarks\n10. Investment thesis: Bull/Bear case`, category: 'analysis', aiTool: 'claude', tags: ['finance', 'financial-analysis', 'investing', 'accounting'], trendingScore: 93, likeCount: 512 },
  { title: 'UX Research Data Synthesizer', content: `Synthesize user research data to extract actionable insights:\n\nResearch type: [INTERVIEWS/USABILITY TESTS/SURVEYS/HEATMAPS]\nProduct: [WHAT YOU'RE RESEARCHING]\nParticipants: [NUMBER AND BRIEF PROFILE]\nKey tasks tested: [LIST]\n\nRaw data/notes:\n[PASTE YOUR RESEARCH NOTES/DATA]\n\nSynthesize into:\n1. Key findings (ranked by frequency/impact)\n2. User pain points and quotes\n3. Mental models revealed\n4. Jobs to be done identified\n5. Usability issues by severity (Critical/Major/Minor)\n6. Positive findings to preserve\n7. Actionable recommendations (prioritized)\n8. Questions for next research sprint`, category: 'analysis', aiTool: 'claude', tags: ['ux-research', 'user-research', 'product', 'insights'], trendingScore: 88, likeCount: 367 },
  { title: 'Root Cause Analysis (5 Whys)', content: `Help me conduct a root cause analysis for this problem:\n\nProblem statement: [DESCRIBE THE ISSUE CLEARLY]\nWhen it occurred: [DATE/FREQUENCY]\nImpact: [WHO/WHAT IS AFFECTED]\nImmediate symptoms: [WHAT YOU CAN OBSERVE]\nWhat you've already tried: [ATTEMPTED FIXES]\n\nApply:\n1. **5 Whys technique** (dig to the root)\n2. **Fishbone diagram** categories (People/Process/Technology/Environment)\n3. Distinguish: symptoms vs. causes vs. root causes\n4. Identify contributing factors\n5. Prioritize root causes by impact\n6. Recommend permanent fixes (not band-aids)\n7. Prevention measures\n8. Monitoring metrics to track improvement`, category: 'analysis', aiTool: 'chatgpt', tags: ['root-cause', 'problem-solving', 'rca', 'troubleshooting'], trendingScore: 90, likeCount: 423 },
  { title: 'Market Sizing Calculator', content: `Help me estimate the market size for [PRODUCT/SERVICE]:\n\nProduct/Service: [DESCRIPTION]\nGeography: [MARKET]\nCustomer type: [B2B/B2C]\nPrimary use case: [HOW IT'S USED]\n\nCalculate using both approaches:\n\n**Top-Down:**\n- Total addressable market (TAM)\n- Serviceable addressable market (SAM)\n- Serviceable obtainable market (SOM)\n\n**Bottom-Up:**\n- Number of potential customers\n- Average deal size/purchase frequency\n- Achievable penetration rate\n\nShow all assumptions clearly. State confidence level for each estimate. Identify the biggest uncertainties.`, category: 'analysis', aiTool: 'claude', tags: ['market-sizing', 'tam-sam-som', 'business', 'startup'], trendingScore: 89, likeCount: 398 },
  { title: 'A/B Test Results Interpreter', content: `Help me interpret my A/B test results:\n\nTest name: [WHAT YOU TESTED]\nHypothesis: [WHAT YOU EXPECTED]\nControl: [DESCRIPTION]\nVariant: [DESCRIPTION]\n\nResults:\n- Control: [VISITORS] visitors, [CONVERSIONS] conversions ([RATE]%)\n- Variant: [VISITORS] visitors, [CONVERSIONS] conversions ([RATE]%)\n- Test duration: [DAYS]\n- Statistical significance: [IF KNOWN]\n\nAnalyze:\n1. Is this result statistically significant?\n2. What's the confidence interval?\n3. Is the sample size sufficient?\n4. Threats to validity (seasonality, novelty effect)\n5. Practical significance vs statistical significance\n6. Recommended decision\n7. Next test to run`, category: 'analysis', aiTool: 'chatgpt', tags: ['ab-testing', 'statistics', 'cro', 'experimentation'], trendingScore: 87, likeCount: 345 },
  { title: 'Customer Churn Analysis', content: `Help me analyze and address customer churn for [PRODUCT/SERVICE]:\n\nChurn rate: [CURRENT RATE]%\nProduct type: [DESCRIPTION]\nCustomer segment: [WHO IS CHURNING]\nChurn window: [WHEN THEY LEAVE - e.g., first 30 days]\nData available: [WHAT METRICS YOU HAVE]\nKnown reasons: [IF ANY EXIT SURVEYS]\n\nAnalyze:\n1. Churn funnel breakdown\n2. Leading indicators of churn (predictive signals)\n3. Segmentation (which customers churn most)\n4. Revenue impact calculation\n5. Comparison to industry benchmarks\n6. Root causes hypothesis\n7. Intervention strategies (prevention > cure)\n8. Winback campaign for churned users\n9. Success metrics to track`, category: 'analysis', aiTool: 'claude', tags: ['churn', 'retention', 'saas', 'customer-success'], trendingScore: 91, likeCount: 456 },
  { title: 'Pricing Strategy Analyzer', content: `Analyze and optimize pricing strategy for [PRODUCT/SERVICE]:\n\nProduct: [DESCRIPTION]\nCurrent price: [PRICE]\nCost to deliver: [COGS]\nCompetitor pricing: [RANGE]\nCustomer segments: [LIST]\nValue delivered: [OUTCOME FOR CUSTOMER]\n\nAnalyze:\n1. Current pricing model assessment\n2. Value-based pricing calculation\n3. Price elasticity estimation\n4. Competitor positioning map\n5. Pricing psychology factors\n6. Tier structure recommendation\n7. Upsell/cross-sell opportunities\n8. Geographic pricing considerations\n9. Price increase strategy and communication\n10. Revenue optimization scenarios`, category: 'analysis', aiTool: 'chatgpt', tags: ['pricing', 'monetization', 'strategy', 'revenue'], trendingScore: 89, likeCount: 412 },
  { title: 'User Behavior Pattern Analyzer', content: `Analyze user behavior patterns from this data:\n\nProduct: [WHAT YOU'RE ANALYZING]\nData source: [ANALYTICS TOOL]\nTime period: [RANGE]\nUser segment: [WHO]\n\nKey metrics:\n[PASTE YOUR METRICS/DATA]\n\nIdentify:\n1. Power user behavior patterns\n2. Activation bottlenecks\n3. Feature adoption rates\n4. Engagement depth and breadth\n5. Cohort retention curves\n6. Drop-off points in key flows\n7. Correlation between behaviors and retention\n8. Leading indicators of success\n9. Segments to target for expansion\n10. Recommended product experiments`, category: 'analysis', aiTool: 'claude', tags: ['analytics', 'user-behavior', 'product', 'growth'], trendingScore: 86, likeCount: 334 },
  { title: 'Scenario Planning Framework', content: `Help me build scenario plans for [BUSINESS/DECISION/SITUATION]:\n\nContext: [CURRENT SITUATION]\nTime horizon: [1/3/5/10 YEARS]\nKey uncertainties: [WHAT COULD GO EITHER WAY]\nCritical success factors: [WHAT MATTERS MOST]\n\nCreate 4 scenarios:\n1. **Best case**: What if everything goes right?\n2. **Base case**: Most likely trajectory\n3. **Downside**: Significant challenges materialize\n4. **Black swan**: Low probability, high impact event\n\nFor each scenario:\n- Narrative description\n- Key assumptions\n- Impact on revenue/costs/operations\n- Trigger signals to watch\n- Recommended strategic response\n- Decisions to make now vs. wait-and-see`, category: 'analysis', aiTool: 'claude', tags: ['scenario-planning', 'strategy', 'risk', 'forecasting'], trendingScore: 88, likeCount: 378 },

  // DESIGN (10)
  { title: 'UI Design System Audit', content: `Audit the following UI design system and provide improvement recommendations:\n\nProduct type: [WEB APP/MOBILE APP/WEBSITE]\nCurrent tech stack: [REACT/VUE/etc.]\nDesign tool: [FIGMA/SKETCH/etc.]\nTeam size: [DESIGNERS + DEVELOPERS]\n\nDescribe current state:\n[DESCRIPTION OR PASTE COMPONENT LIST]\n\nAudit against:\n1. Consistency (naming conventions, patterns)\n2. Accessibility (WCAG 2.1 AA compliance)\n3. Component coverage (what's missing)\n4. Token usage (colors, typography, spacing)\n5. Documentation quality\n6. Developer handoff efficiency\n7. Performance implications\n\nPrioritize findings: Critical/High/Medium/Low\nProvide actionable improvement plan.`, category: 'design', aiTool: 'claude', tags: ['design-system', 'ui', 'ux', 'component-library'], trendingScore: 90, likeCount: 423 },
  { title: 'UX Copy Writer', content: `Write UX copy for the following interface elements:\n\nProduct: [PRODUCT NAME AND TYPE]\nUser action: [WHAT THE USER IS DOING]\nContext: [WHERE IN THE APP]\nBrand voice: [FRIENDLY/PROFESSIONAL/PLAYFUL]\n\nWrite copy for:\n1. Empty state (no content yet)\n2. Error message (something went wrong)\n3. Success confirmation\n4. Onboarding step [STEP NUMBER]\n5. Tooltip for [FEATURE]\n6. Button labels (primary + secondary)\n7. Form field labels and placeholder text\n8. Loading state message\n9. Delete/destructive action confirmation\n10. Feature announcement banner\n\nEach under 15 words. Human, clear, action-oriented.`, category: 'design', aiTool: 'claude', tags: ['ux-writing', 'microcopy', 'ui-text', 'content-design'], trendingScore: 88, likeCount: 378 },
  { title: 'Color Palette Generator Brief', content: `Create a comprehensive color palette for [BRAND/PROJECT]:\n\nBrand/Project: [NAME]\nIndustry: [SECTOR]\nTarget audience: [WHO]\nPersonality adjectives: [3-5 WORDS e.g., "bold, modern, trustworthy"]\nCompetitors to differentiate from: [BRANDS]\nExisting constraints: [LOGO COLORS/EXISTING ELEMENTS]\n\nDefine:\n1. Primary color (with hex + rationale)\n2. Secondary color\n3. Accent color\n4. Neutral scale (5-6 grays)\n5. Semantic colors (success/warning/error/info)\n6. Dark mode variants\n7. Accessibility check (contrast ratios)\n8. Usage guidelines per color\n9. Color psychology explanation\n10. Combinations to use and avoid`, category: 'design', aiTool: 'chatgpt', tags: ['color', 'brand', 'palette', 'design-system'], trendingScore: 92, likeCount: 489 },
  { title: 'Information Architecture Planner', content: `Design the information architecture for [WEBSITE/APP]:\n\nProduct: [DESCRIPTION]\nUser goals: [TOP 3 THINGS USERS WANT TO DO]\nContent volume: [HOW MANY PAGES/SCREENS]\nMain user type: [PRIMARY PERSONA]\nExisting structure: [IF REDESIGN, DESCRIBE CURRENT]\n\nCreate:\n1. Sitemap (hierarchical structure)\n2. Navigation taxonomy (primary/secondary/utility nav)\n3. Content categorization rationale\n4. Labeling guidelines\n5. Search and filter requirements\n6. Cross-linking strategy\n7. User journey flows (3 main journeys)\n8. Card sorting insights (if applicable)\n9. Mobile navigation adaptation\n10. Breadcrumb and wayfinding system`, category: 'design', aiTool: 'claude', tags: ['information-architecture', 'sitemap', 'ux', 'navigation'], trendingScore: 87, likeCount: 345 },
  { title: 'Accessibility Checklist Reviewer', content: `Review this design/interface for accessibility issues:\n\nInterface type: [WEB PAGE/MOBILE APP/COMPONENT]\nDescription or screenshots: [DESCRIBE THE UI]\nKnown user base: [INCLUDE USERS WITH DISABILITIES?]\nCompliance target: [WCAG 2.1 A/AA/AAA]\n\nCheck against WCAG 4 principles (POUR):\n\n**Perceivable**\n- Color contrast ratios\n- Alt text for images\n- Captions for media\n\n**Operable**\n- Keyboard navigation\n- Focus indicators\n- Skip links\n\n**Understandable**\n- Clear language\n- Error identification\n- Consistent navigation\n\n**Robust**\n- Semantic HTML\n- ARIA usage\n- Cross-browser compatibility\n\nPrioritize: Critical/High/Medium/Low`, category: 'design', aiTool: 'claude', tags: ['accessibility', 'wcag', 'a11y', 'inclusive-design'], trendingScore: 89, likeCount: 398 },
  { title: 'User Onboarding Flow Designer', content: `Design an effective onboarding flow for [PRODUCT]:\n\nProduct: [DESCRIPTION]\nKey activation metric: [WHAT MAKES A USER "ACTIVATED"]\nUser type: [B2B/B2C, technical level]\nOnboarding goal: [WHAT USERS MUST ACHIEVE]\nTime to value: [HOW QUICKLY THEY SHOULD SEE VALUE]\n\nDesign:\n1. Welcome screen copy and CTA\n2. Progressive profiling questions (max 3)\n3. Empty state experiences\n4. Tooltips and coach marks strategy\n5. Progress indicator design\n6. First success moment design\n7. Email drip integration touchpoints\n8. Skip/defer options\n9. Returning user experience\n10. A/B test recommendations for optimization`, category: 'design', aiTool: 'claude', tags: ['onboarding', 'ux', 'product-design', 'activation'], trendingScore: 91, likeCount: 456 },
  { title: 'Design Critique Framework', content: `Provide a structured design critique for this design:\n\nDesign type: [UI/BRAND/PRINT/PRODUCT/etc.]\nDesign goal: [WHAT IT SHOULD ACHIEVE]\nTarget audience: [WHO IT'S FOR]\nBusiness context: [CONSTRAINTS OR REQUIREMENTS]\n\nDescribe the design: [PASTE DESCRIPTION OR LINK]\n\nCritique across:\n1. **Visual hierarchy**: Does the eye go to the right places?\n2. **Clarity**: Is the purpose immediately clear?\n3. **Consistency**: Does it follow established patterns?\n4. **Aesthetics**: Does it achieve the intended feel?\n5. **Functionality**: Does it solve the user's problem?\n6. **Technical feasibility**: Can it be implemented?\n\nBalance: What's working / What needs improvement / Specific suggestions`, category: 'design', aiTool: 'claude', tags: ['design-critique', 'feedback', 'ux', 'visual-design'], trendingScore: 85, likeCount: 312 },
  { title: 'Typography Pairing Guide', content: `Create a typography system for [PROJECT TYPE]:\n\nProject: [WEBSITE/APP/BRAND]\nPersonality: [ELEGANT/MODERN/PLAYFUL/TECHNICAL/etc.]\nContent types: [HEADINGS/BODY/UI/DISPLAY]\nTech stack: [WEB/NATIVE/PRINT]\nBudget for fonts: [FREE/LICENSED]\n\nProvide:\n1. Primary font recommendation + rationale\n2. Secondary font for contrast\n3. Monospace font (if needed)\n4. Type scale (px + rem values)\n5. Line height recommendations\n6. Letter spacing rules\n7. Font weight usage guide\n8. Responsive type behavior\n9. Accessibility considerations (min sizes)\n10. Loading performance tips for web fonts`, category: 'design', aiTool: 'chatgpt', tags: ['typography', 'fonts', 'design-system', 'brand'], trendingScore: 86, likeCount: 334 },
  { title: 'Landing Page UX Optimizer', content: `Analyze and optimize this landing page for conversions:\n\nProduct/Service: [WHAT YOU'RE SELLING]\nTarget audience: [WHO LANDS ON THIS PAGE]\nTraffic source: [HOW THEY ARRIVE]\nPrimary CTA: [DESIRED ACTION]\nCurrent conversion rate: [IF KNOWN]\n\nPage sections to review:\n[DESCRIBE YOUR CURRENT PAGE STRUCTURE]\n\nOptimize:\n1. Above-the-fold impact\n2. Value proposition clarity\n3. Visual hierarchy and scan patterns\n4. CTA placement and design\n5. Social proof integration\n6. Trust signals\n7. Form optimization (if applicable)\n8. Mobile experience\n9. Page speed impact on UX\n10. Specific rewrite recommendations`, category: 'design', aiTool: 'claude', tags: ['landing-page', 'conversion', 'cro', 'ux'], trendingScore: 93, likeCount: 512 },
  { title: 'Wireframe to Prototype Brief', content: `Create a detailed wireframe specification for [SCREEN/FEATURE]:\n\nFeature: [WHAT YOU'RE DESIGNING]\nUser goal: [WHAT THE USER WANTS TO ACCOMPLISH]\nContext: [WHERE IN THE APP/SITE]\nKey data to display: [CONTENT REQUIREMENTS]\nUser actions: [WHAT THEY SHOULD BE ABLE TO DO]\n\nSpecify:\n1. Layout grid (columns/gutters)\n2. Component list with descriptions\n3. Interactive elements and states\n4. Navigation patterns\n5. Content hierarchy\n6. Error and empty states\n7. Loading states\n8. Responsive breakpoint behavior\n9. Micro-interaction notes\n10. Handoff annotations for developers`, category: 'design', aiTool: 'claude', tags: ['wireframe', 'prototype', 'ui', 'product-design'], trendingScore: 84, likeCount: 289 },

  // OTHER (10)
  { title: 'Personal Assistant Daily Briefing', content: `Act as my personal AI assistant and give me a comprehensive morning briefing.\n\nToday is: [DATE]\nMy priorities: [TOP 3 GOALS]\nSchedule: [KEY EVENTS TODAY]\nLocation: [CITY]\nCurrent projects: [BRIEF LIST]\n\nBriefing should include:\n1. Weather and its impact on my day\n2. Key events happening today (my schedule)\n3. Top 3 focus areas ranked by importance\n4. Potential challenges and how to handle them\n5. One motivational insight based on my goals\n6. Evening intention (what would make today a success?)\n\nBe direct, practical, and energizing. No fluff.`, category: 'other', aiTool: 'chatgpt', tags: ['personal-assistant', 'daily-planning', 'morning-routine'], trendingScore: 88, likeCount: 389 },
  { title: 'Recipe Creator from Ingredients', content: `Create a recipe using only these ingredients I have:\n\nIngredients available: [LIST EVERYTHING IN YOUR FRIDGE/PANTRY]\nDietary restrictions: [VEGAN/GLUTEN-FREE/DAIRY-FREE/etc. or NONE]\nCooking skill: [BEGINNER/INTERMEDIATE/ADVANCED]\nTime available: [MINUTES]\nServings needed: [NUMBER]\nEquipment: [LIST AVAILABLE COOKWARE]\n\nCreate:\n1. Recipe name and description\n2. Full ingredient list with measurements\n3. Step-by-step instructions\n4. Tips for best results\n5. Variations with similar ingredients\n6. Nutritional highlights\n7. Wine/drink pairing (optional)\n\nPrioritize using ingredients that need to be used soon.`, category: 'other', aiTool: 'chatgpt', tags: ['recipe', 'cooking', 'food', 'meal-planning'], trendingScore: 91, likeCount: 445 },
  { title: 'Travel Itinerary Planner', content: `Create a detailed travel itinerary for [DESTINATION]:\n\nDestination: [CITY/COUNTRY]\nDuration: [NUMBER] days\nDates: [DATE RANGE]\nTravelers: [SOLO/COUPLE/FAMILY with ages]\nBudget: [BUDGET LEVEL - budget/mid-range/luxury]\nInterests: [HISTORY/FOOD/ADVENTURE/CULTURE/ART/etc.]\nPhysical limitations: [IF ANY]\n\nFor each day provide:\n- Morning activity (with opening times)\n- Lunch recommendation\n- Afternoon activity\n- Dinner recommendation (with price range)\n- Evening suggestion\n- Transportation tips\n- Estimated costs\n\nAlso: Packing list, must-know local tips, what to avoid.`, category: 'other', aiTool: 'chatgpt', tags: ['travel', 'itinerary', 'planning', 'tourism'], trendingScore: 93, likeCount: 512 },
  { title: 'Difficult Conversation Script', content: `Help me prepare for a difficult conversation with [PERSON]:\n\nRelationship: [BOSS/COLLEAGUE/PARTNER/FRIEND/FAMILY]\nIssue to address: [WHAT NEEDS TO BE DISCUSSED]\nDesired outcome: [WHAT YOU WANT TO ACHIEVE]\nTheir likely reaction: [HOW YOU THINK THEY'LL RESPOND]\nYour concern: [WHAT YOU'RE AFRAID MIGHT HAPPEN]\n\nPrepare:\n1. Opening line (direct but not aggressive)\n2. How to state the issue clearly\n3. Active listening prompts\n4. How to handle [SPECIFIC DIFFICULT RESPONSE]\n5. De-escalation phrases if it gets heated\n6. Closing that preserves the relationship\n7. What NOT to say\n8. Best time/setting to have this conversation`, category: 'other', aiTool: 'claude', tags: ['communication', 'conflict', 'relationships', 'emotional-intelligence'], trendingScore: 90, likeCount: 423 },
  { title: 'Fitness Plan Creator', content: `Create a personalized fitness plan:\n\nGoal: [LOSE WEIGHT/BUILD MUSCLE/IMPROVE ENDURANCE/GENERAL FITNESS]\nCurrent fitness level: [BEGINNER/INTERMEDIATE/ADVANCED]\nAge: [AGE]\nAvailable time: [DAYS/WEEK] x [MINUTES/SESSION]\nEquipment access: [GYM/HOME/BODYWEIGHT ONLY]\nPhysical limitations: [INJURIES/CONDITIONS]\nDiet preference: [IF RELEVANT]\n\nProvide:\n1. Weekly workout schedule\n2. Each workout with exercises, sets, reps, rest\n3. Progressive overload plan (week-by-week)\n4. Warm-up and cool-down routines\n5. Nutrition guidelines (macros if relevant)\n6. Recovery strategy\n7. Progress tracking metrics\n8. 12-week milestone targets`, category: 'other', aiTool: 'chatgpt', tags: ['fitness', 'workout', 'health', 'exercise'], trendingScore: 92, likeCount: 478 },
  { title: 'Investment Research Template', content: `Help me research [STOCK/CRYPTO/INVESTMENT] as a potential investment:\n\nAsset: [NAME/TICKER]\nInvestment size: [AMOUNT]\nTime horizon: [MONTHS/YEARS]\nRisk tolerance: [LOW/MEDIUM/HIGH]\nPortfolio context: [HOW IT FITS YOUR PORTFOLIO]\n\nResearch framework:\n1. Business model (how it makes money)\n2. Competitive moat assessment\n3. Financial health (key ratios)\n4. Growth drivers and catalysts\n5. Risk factors and bear case\n6. Valuation analysis (DCF/multiples)\n7. Management quality indicators\n8. Industry tailwinds and headwinds\n9. Entry point considerations\n10. Position sizing recommendation\n\n*Note: This is for research only, not financial advice.*`, category: 'other', aiTool: 'chatgpt', tags: ['investing', 'finance', 'stocks', 'research'], trendingScore: 89, likeCount: 412 },
  { title: 'Life Coach Session Simulation', content: `Act as a professional life coach and conduct a coaching session with me.\n\nMy situation: [DESCRIBE WHAT'S ON YOUR MIND]\nWhat I want from this session: [CLARITY/MOTIVATION/PLAN/PERSPECTIVE]\nArea of focus: [CAREER/RELATIONSHIPS/HEALTH/MEANING/FINANCES]\nWhat I've already tried: [PAST ATTEMPTS]\n\nCoaching approach:\n- Ask powerful questions instead of giving answers\n- Use the GROW model (Goal, Reality, Options, Will)\n- Help me identify my own blind spots\n- Challenge assumptions gently\n- Reflect patterns you notice\n- End with a clear commitment and action\n\nStart with: "What would make this session most valuable for you today?"`, category: 'other', aiTool: 'claude', tags: ['life-coaching', 'personal-development', 'mindset', 'growth'], trendingScore: 87, likeCount: 356 },
  { title: 'Home Renovation Planner', content: `Help me plan a home renovation project:\n\nProject: [KITCHEN/BATHROOM/LIVING ROOM/etc.]\nBudget: [TOTAL BUDGET]\nTimeline: [WHEN YOU WANT IT DONE]\nDIY capability: [CAN DO MYSELF/HIRE ALL/MIXED]\nGoals: [AESTHETIC/FUNCTIONALITY/RESALE VALUE/etc.]\nCurrent state: [DESCRIBE WHAT EXISTS NOW]\nMust-haves: [NON-NEGOTIABLES]\n\nProvide:\n1. Project scope definition\n2. Priority list (what gets the most ROI)\n3. Budget allocation breakdown\n4. Timeline with milestones\n5. Contractor roles needed\n6. Permit requirements (typical)\n7. Common mistakes to avoid\n8. Inspiration directions to explore\n9. Questions to ask contractors\n10. Cost-saving strategies`, category: 'other', aiTool: 'chatgpt', tags: ['home', 'renovation', 'planning', 'real-estate'], trendingScore: 85, likeCount: 312 },
  { title: 'Mental Health Check-In Companion', content: `Act as a supportive companion for a mental health check-in.\n\nMy emotional state today: [HOW YOU'RE FEELING]\nMain stressor: [WHAT'S ON YOUR MIND]\nPhysical state: [SLEEP/ENERGY LEVEL]\nWhat I need right now: [VENTING/ADVICE/PERSPECTIVE/GROUNDING]\n\nApproach:\n1. Acknowledge my feelings without judgment\n2. Help me identify what's within and outside my control\n3. Offer grounding technique if overwhelmed\n4. Reframe one negative thought pattern\n5. Suggest one small action I can take today\n6. Check what support system I have\n7. End with an affirming, realistic statement\n\n*Note: This is not therapy. For serious concerns, please seek professional help.*`, category: 'other', aiTool: 'claude', tags: ['mental-health', 'wellbeing', 'emotional-support', 'mindfulness'], trendingScore: 86, likeCount: 334 },
  { title: 'Gift Idea Generator', content: `Help me find the perfect gift for [PERSON]:\n\nRecipient: [RELATIONSHIP]\nAge: [AGE]\nGender: [OPTIONAL]\nInterests/Hobbies: [LIST WHAT THEY ENJOY]\nOccasion: [BIRTHDAY/ANNIVERSARY/HOLIDAY/etc.]\nBudget: [RANGE]\nKnown items they already have: [IF ANY]\nPersonality: [INTROVERT/EXTROVERT, PRACTICAL/SENTIMENTAL]\nDelivery: [IN PERSON/SHIP TO THEM]\n\nSuggest:\n1. 3 premium picks (top of budget)\n2. 3 mid-range options\n3. 3 budget-friendly choices\n4. 1 unique experience gift\n5. 1 personalized/sentimental option\n\nFor each: Why they'll love it, where to buy it, how to personalize it.`, category: 'other', aiTool: 'chatgpt', tags: ['gift', 'ideas', 'shopping', 'occasions'], trendingScore: 88, likeCount: 367 },
];

async function main() {
  if (!MONGO_URI) {
    console.error('MONGODB_URI not set');
    process.exit(1);
  }

  await mongoose.connect(MONGO_URI);
  console.log('Connected to MongoDB');

  // Ensure a seed user exists
  const UserModel = mongoose.models.User || mongoose.model('User', new mongoose.Schema({
    name: String, username: String, email: String, password: String,
    provider: String, role: String, promptCount: Number, likeCount: Number,
  }, { timestamps: true }));

  let seedUser = await UserModel.findOne({ username: SEED_USER.username });
  if (!seedUser) {
    seedUser = await UserModel.create({
      _id: SEED_USER._id,
      name: SEED_USER.name,
      username: SEED_USER.username,
      email: 'team@promptall.net',
      provider: 'email',
      role: 'admin',
      promptCount: 0,
      likeCount: 0,
    });
    console.log('Created seed user');
  }

  const PromptModel = mongoose.models.Prompt || mongoose.model('Prompt', new mongoose.Schema({
    title: String, content: String, description: String, aiTool: String, category: String,
    tags: [String], resultText: String, resultImages: [String], resultLink: String,
    author: mongoose.Schema.Types.ObjectId, authorName: String, authorUsername: String,
    likeCount: Number, commentCount: Number, bookmarkCount: Number,
    viewCount: Number, copyCount: Number, trendingScore: Number,
    status: String, reportCount: Number, slug: String, language: String,
  }, { timestamps: true }));

  let inserted = 0;
  for (const p of PROMPTS) {
    const s = slug(p.title);
    try {
      await PromptModel.create({
        title: p.title,
        content: p.content,
        aiTool: p.aiTool,
        category: p.category,
        tags: p.tags || [],
        resultImages: [],
        author: seedUser._id,
        authorName: seedUser.name,
        authorUsername: seedUser.username,
        likeCount: p.likeCount || 0,
        commentCount: 0,
        bookmarkCount: 0,
        viewCount: Math.floor(Math.random() * 5000) + 500,
        copyCount: Math.floor(Math.random() * 1000) + 100,
        trendingScore: p.trendingScore || 50,
        status: 'active',
        reportCount: 0,
        slug: s,
        language: 'en',
      });
      inserted++;
      process.stdout.write(`\rInserted ${inserted}/${PROMPTS.length}`);
    } catch (e: any) {
      console.error(`\nFailed: ${p.title} - ${e.message}`);
    }
  }

  await UserModel.findByIdAndUpdate(seedUser._id, { promptCount: inserted });
  console.log(`\nDone! Inserted ${inserted} prompts.`);
  await mongoose.disconnect();
}

main().catch(console.error);
